### ISSUE TITLE
CI cache: API error (429 Too Many Requests)

### ISSUE THREAD

**Issue by mightyiam** [ngi-nix/ngipkgs#102]
https://github.com/ngi-nix/ngipkgs/actions/runs/7025704296/job/19117044773?pr=100#step:8:490

**Comment by mightyiam** [comment]
https://github.com/DeterminateSystems/magic-nix-cache#usage-notes

---

## Usage Notes

The GitHub Actions Cache has a rate limit on reads and writes.
Occasionally, large projects or large rebuilds may exceed those rate-limits, and you'll see evidence of that in your logs.
The error looks like this:

```
error: unable to download 'http://127.0.0.1:37515/<...>': HTTP error 418
       response body:
       GitHub API error: API error (429 Too Many Requests): StructuredApiError { message: "Request was blocked due to exceeding usage of resource 'Count' in namespace ''." }
```

The caching daemon and Nix both handle this gracefully, and won't cause your CI to fail.
When the rate limit is exceeded while pulling dependencies, your workflow may perform more builds than usual.
When the rate limit is exceeded while uploading to the cache, the remainder of those store paths will be uploaded on the next run of the workflow.

---

Not ideal, but we must pick our battles.

**Comment by lorenzleutgeb** [comment]
Not applicable anymore since Magic Nix Cache was removed in https://github.com/ngi-nix/ngipkgs/pull/181/files#diff-7b2a967de7060a238e49a57908f83e860b8cb53a0b0991c3d0d275857c1014d4L20
