### ISSUE TITLE
Do NixOS configs belong in `packages` output?

### ISSUE THREAD

**Issue by mightyiam** [ngi-nix/ngipkgs#108]
@lorenzleutgeb

In the `packages` output, I see packages such as flarum-toplevel and kbin-toplevel.

They appear to be NixOS configurations.

From #53:

> Additionally, toplevel derivations are now packages, which means that `nix check` will catch mistakes in our `nixosConfigurations`.

Is `nix flake check` building (or is it only evaluating?) those configurations the only purpose for their inclusion in the `packages` output?

If so, I'd like to suggest it may be cleaner to find a way to include them in the `checks` output, instead. Your feedback, please.

**Comment by lorenzleutgeb** [comment]
It was also handy to have them around in `packages` sometimes. E.g. you want to check the system "state" (well, only it's toplevel, but that means many files are already linked to the correct place) of a config while working on a NixOS test. Building a NixOS test is much more time consuming than just the toplevel. But of course it's also possible to `nix build .#checks.[...]`, so I am okay with having toplevels in checks only.
