### ISSUE TITLE
NixOS tests are not in flake checks

### ISSUE THREAD

**Issue by mightyiam** [ngi-nix/ngipkgs#157]
I can't find where NixOS tests are in flake checks. I thought they are the ones postfixed `-toplevel` but those seem to be merely the example NixOS configurations.

I can see the NixOS tests under `hydraJobs.tests.x86_64-linux`.

I feel like they should be there... No? Is it too much for the local workflow?

**Comment by lorenzleutgeb** [comment]
The reason is mentioned in https://github.com/ngi-nix/ngipkgs/issues/28#issuecomment-1690601585

`nix flake check` should be reasonably fast, and NixOS tests are not fast. They are however still contained in the hydra jobs, which are less time-critical, as you mention.

**Comment by mightyiam** [comment]
Okay. Thank you.
