### ISSUE TITLE
Migrate `weblate`

### ISSUE THREAD

**Issue by lorenzleutgeb** [ngi-nix/ngipkgs#221]
### Repository URL

https://github.com/ngi-nix/weblate

### Notes

I saw that there's activity in that Flake by @erictapen and it's [on Flakestry](https://flakestry.dev/flake/github/ngi-nix/weblate).

**Comment by wegank** [comment]
Does this mean introducing poetry2nix support in the repo? I tried to package Weblate with dream2nix, but failed because of nix-community/dream2nix#745.

**Comment by erictapen** [comment]
Ah I think now I understand the goal of this issue. Feel free to ping me for questions on this.

**Comment by lorenzleutgeb** [comment]
Sorry @erictapen, more context is here: #12
