### ISSUE TITLE
lib25519

### ISSUE THREAD

**Issue by jleightcap** [ngi-nix/ngipkgs#249]
> lib25519 is a microlibrary for the X25519 encryption system and the Ed25519 signature system, both of which use the Curve25519 elliptic curve. Curve25519 is the fastest curve in TLS 1.3, and the only curve in Wireguard, Signal, and many other applications (see Nicolai Brown's page https://ianix.com/pub/curve25519-deployment.html).

nixpkgs PRs:
- `librandombytes` https://github.com/NixOS/nixpkgs/pull/317781
- `libcpucycles` https://github.com/NixOS/nixpkgs/pull/319608
- `lib25519` https://github.com/NixOS/nixpkgs/pull/319618

**Comment by imadnyc** [comment]
# done 
+ confirmed that stripping and correct CFLAGS being used
