### ISSUE TITLE
Vula GUI fails to start

### ISSUE THREAD

**Issue by adfaure** [ngi-nix/ngipkgs#277]
The GUI is optional.
It will take some more packaging work.

**Comment by mightyiam** [comment]
Some more background: #240 was intentionally merged with broken GUI in the name of progress.

Today we made progress on GUI. The GUI works. It just needed a couple of dependencies.

Still on the todo:

- desktop file or two (vula gui, vula tray)
- systemd service unit file for vula tray.

Progress is in branch `mob/vula-gui`.

**Comment by ioerror** [comment]
The vula gui and vula tray are distinct. Of note is that the tray will open the gui if the correct item is selected.

Is the vula tray systemd unit file a systemd user service? That seems like a good idea and we'd probably like to include such a service configuration upstream.

**Comment by mightyiam** [comment]
We're going for a .desktop file, not a systemd user service.

**Comment by mightyiam** [comment]
@ioerror just wanted to let you know that @ngi-nix/cake and @ngi-nix/magic hope to return to this after #139.
