### ISSUE TITLE
Support for NixOS tests

### ISSUE THREAD

**Issue by cleeyv** [ngi-nix/ngipkgs#28]
NixOS tests are a powerful tool for writing automated VM-based integration tests of complex and high-level software functionality. It would be great to have support for them in Ngipkgs. One of the main questions is where they would run. On nixpkgs they run on hydra so hopefully we can do the same on hydra.ngi0.nixos.org. 

Some links to relevant documentation:
https://nixos.org/manual/nixos/stable/index.html#sec-nixos-tests
https://nix.dev/tutorials/nixos/integration-testing-using-virtual-machines

**Comment by lorenzleutgeb** [comment]
We've started using NixOS tests for pretalx. It's still work in progress...

https://github.com/ngi-nix/ngipkgs/blob/f4af99d686368732d92ef4c84be6c27f94e539e4/flake.nix#L55-L56

We put the test itself under `tests/pretalx/`.
https://github.com/ngi-nix/ngipkgs/blob/f4af99d686368732d92ef4c84be6c27f94e539e4/tests/pretalx/pretalx.nix

Just noting this here, in case someone else works in that direction...

**Comment by cleeyv** [comment]
Thanks for sharing this, @lorenzleutgeb ! There was also recently discussion of this on matrix recently where you shared these additional details that I think are very helpful for anyone using this for local interactive testing of a web service:
> This will drop you into a shell, where you can enter `start_all()`. Then you'll get a QEMU VM. You can log in as root without a password. After some booting (it's quite slow), you should first get HTTP 502 for `curl localhost` (as pretalx is still initializing), and once pretalx is up you'll get some Website at `curl localhost`. To use your browser, in the "driver shell", run `server.forward_port(8000, 80)` or so (first argument is your host, second argument is the testing VM port).

**Comment by cleeyv** [comment]
The remaining integration of nixos-tests into the hydra CI has been completed with commit https://github.com/ngi-nix/ngipkgs/commit/1153203fdf9d98643350666de4415c486d0a3e2b which adds the `nixosTests` output to`hydraJobs` in the flake. Hydra reports that the test is building successfully, https://hydra.ngi0.nixos.org/eval/1274 and the logs show that the test is running: https://hydra.ngi0.nixos.org/build/3029/nixlog/385

**Comment by lorenzleutgeb** [comment]
I'd like to remind ourselves, that the output `nixosTests` was chosen relatively ad hoc by @ngi-nix/algae and should be reconsidered. If possible, I'd like to use passthrus, just like in nixpkgs.

The idea that Hydra should just pick up passthrus is not new: https://github.com/NixOS/nixpkgs/issues/136026

In the meantime, I propose to at least wire `nixosTests` into our `callPackage` context, such that we can use it like in nixpkgs: https://github.com/ngi-nix/ngipkgs/pull/52
