### ISSUE TITLE
Gancio

### ISSUE THREAD

**Issue by fricklerhandwerk** [ngi-nix/ngipkgs#337]
Shared agenda for local communities that supports Activity Pub, written in JavaScript.

- NLnet project: https://nlnet.nl/project/Gancio/
- Source code: https://framagit.org/les/gancio

**Comment by erictapen** [comment]
There is an ongoing effort to get a gancio module into Nixpkgs: https://github.com/NixOS/nixpkgs/pull/279011

**Comment by erictapen** [comment]
Closed in https://github.com/NixOS/nixpkgs/pull/279011
