### ISSUE TITLE
Open Web Calendar

### ISSUE THREAD

**Issue by fricklerhandwerk** [ngi-nix/ngipkgs#340]
The Open Web Calendar stack is an open-source set of Python libraries and programs which read and write calendars based on the iCalendar standard. The Open Web Calendar displays a highly configurable website that can be embedded to show a calendar. Currently, ICS URLs are supported and a goal is to also support CalDAV.

- NLnet project: https://nlnet.nl/project/OpenWebCalendar/
- Source code:  https://github.com/niccokunzmann/open-web-calendar

**Comment by erictapen** [comment]
Author is asking for upstream docs on how to install it on NixOS: https://github.com/niccokunzmann/open-web-calendar/issues/649

**Comment by fricklerhandwerk** [comment]
@erictapen this is https://github.com/ngi-nix/ngipkgs/issues/516
