### ISSUE TITLE
Migrate `alliance`

### ISSUE THREAD

**Issue by alejandrosame** [ngi-nix/ngipkgs#64]
https://github.com/ngi-nix/alliance

part of https://github.com/ngi-nix/ngipkgs/issues/12

**Comment by alejandrosame** [comment]
This package vendors the source code inside the repo ([reference](https://github.com/ngi-nix/alliance/blob/991d3a8b1e11c5613d792480c2b0e3a144a11041/flake.nix#L35)).

Should it be moved to `ngipkgs` as it is? Or should this be amended when transitioning it to the monorepo?

**Comment by lorenzleutgeb** [comment]
Please don't vendor the whole thing. Most recent version I found is

```console
> nix-prefetch-url 'http://www-asim.lip6.fr/pub/alliance/distribution/5.0/alliance-5.1.1.tar.bz2'
path is '/nix/store/6775m4zbbh5j4if2avf8bx1l5c3r5w1l-alliance-5.1.1.tar.bz2'
046c9qwl1vbww0ljm4xyxf5jpz9nq62b2q0wdz9xjimgh4c207w1
```

But I don't think that this is the version that's vendored. You may try if it builds, otherwise try to find the vendored one via http://www-asim.lip6.fr/pub/alliance/

**Comment by augustebaum** [comment]
Alliance [is in nixpkgs](https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/applications/science/electronics/alliance/default.nix), and its description starts with "(deprecated)".

It is a collection of many C programs that are independent for the most part, grouped into a single derivation; thus, if a single one of the programs fails to build, the whole build fails. If there is work to be done here it would be splitting it up into many derivations, but considering the previous points I would recommend closing this issue.
