### ISSUE TITLE
Migrate `arpa2`

### ISSUE THREAD

**Issue by alejandrosame** [ngi-nix/ngipkgs#66]
https://github.com/ngi-nix/arpa2

**Comment by alejandrosame** [comment]
@ngi-nix/fungus is working on this

**Comment by mightyiam** [comment]
Me and @augustebaum are working on this. But we can use some help. There's some dependency resolution problem. An ancient library called comerr or similar. If anyone would be kind enough to join us for a session and help out with this problem, that would be fantastic.

@fricklerhandwerk @lorenzleutgeb

**Comment by mightyiam** [comment]
That problem has been solved by now. Thanks to @tfc who really seems to know what he's doing.
