### ISSUE TITLE
Migrate `scion`

### ISSUE THREAD

**Issue by augustebaum** [ngi-nix/ngipkgs#69]
https://github.com/ngi-nix/scion

part of https://github.com/ngi-nix/ngipkgs/issues/12

Current state:
- Uses `buildGo117Module` for most packages, which is not provided by our nixpkgs version.
- Has some tests, but `nix flake check` fails:
```
 '/nix/store/3vc2g0frp09zjkbfdpmj9dlkv25ddp67-source/19-ffaa_1_fe3.tar.gz': No such file or directory
```
and indeed the file is missing.
- `nix build .#scion` works.
- Provides some modules as well as the packages.

---

I tried to build it using `buildGoModule` just to check and got this error:
```
vendor/github.com/lucas-clemente/quic-go/internal/qtls/go118.go:5:13:
cannot use "quic-go doesn't build on Go 1.18 yet." (untyped string constant) as int value in variable declaration
```
which seems to suggest there are upstream dependencies that need to be updated before this flake can be ported, as per [this recommendation](https://github.com/NixOS/nixpkgs/issues/192333).

**Comment by augustebaum** [comment]
Turns out @sarcasticadmin has been able to bump the Go toolchain version: https://github.com/ngi-nix/scion/pull/7

**Comment by mightyiam** [comment]
It seems that `nix flake check` is failing in `master` of the `ngi-nix/scion` repository. And we're not sure it is trivial, so we'll see whether easier tasks are available.

**Comment by sarcasticadmin** [comment]
Theres some remaining upstream work in `scion-apps` (https://github.com/netsec-ethz/scion-apps/pull/246) that Im waiting on. But once that lands the drvs in `ngi-nix/scion` should be much more update to date.

**Comment by sarcasticadmin** [comment]
@mightyiam @augustebaum @lorenzleutgeb All of the upstream work has landed so the PR https://github.com/ngi-nix/scion/pull/7 is ready for review

**Comment by fricklerhandwerk** [comment]
Closing, as SCION is already being landed in Nixpkgs https://github.com/NixOS/nixpkgs/pull/298737
