### ISSUE TITLE
Re-Export from nixpkgs

### ISSUE THREAD

**Issue by lorenzleutgeb** [ngi-nix/ngipkgs#76]
- [Rosenpass](https://github.com/NixOS/nixpkgs/pull/254813)
 - [Librecast](https://github.com/NixOS/nixpkgs/pull/248437)
 - [Flarum](https://github.com/NixOS/nixpkgs/pull/311608/)

**Comment by cipharius** [comment]
* [arcan](https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/ar/arcan/package.nix)

Specifically A12 protocol libraries and arcan-net server/client binary, which is [part of NlNet project](https://nlnet.nl/project/Arcan-A12/). The package builds the whole arcan project though.

**Comment by fricklerhandwerk** [comment]
Finished for the projects listed in the top comment.
