### ISSUE TITLE
Kbin

### ISSUE THREAD

**Issue by fricklerhandwerk** [ngi-nix/ngipkgs#9]
Kbin is a decentralized content aggregator and microblogging platform running on the Fediverse network. It can communicate with many other ActivityPub services, including Mastodon, Lemmy, Pleroma, Peertube.

- [NLnet project](https://nlnet.nl/project/Kbin)
- [source code](https://codeberg.org/Kbin/kbin-core)

Project seems to be medium-sized, is alive and very active, and not packaged anywhere yet.

**Comment by cleeyv** [comment]
Within a day of this issue being created, a packaging request for Kbin was opened on nixpkgs: https://github.com/NixOS/nixpkgs/issues/237307
A few days later, it already has a number of :+1: reactions. Any SoN work happening here should be reported on the nixpkgs issue, and if the work is completed then it should definitely be considered for contribution to nixpkgs.
